import type { NextPage } from "next";
import Head from "next/head";
import TopBar from "../components/Topbar";
import Login from "./login";

const Home: NextPage = () => {
  return (
    <div className="w-screen h-screen bg-gray-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </div>
  );
};

export default Home;
