version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-geek
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: geeklist
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-geek
    command: redis-server --requirepass RedisFindit
    ports:
      - '6379:6379'
